# Generated by Django 4.1.2 on 2022-10-12 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('doctorPicture', models.ImageField(upload_to='doctorPics')),
                ('houspitalName', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('services', models.TextField(max_length=500)),
            ],
        ),
    ]
