# Generated by Django 4.1.2 on 2022-11-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0002_doctor_detail_meeting_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='blogThumbnail')),
                ('content', models.TextField()),
            ],
        ),
    ]
