# Generated by Django 4.1.2 on 2022-11-27 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0003_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
