# Generated by Django 4.1.2 on 2022-11-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0004_blogs_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
